//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entityes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALevelProjectEntities : DbContext
    {
        public ALevelProjectEntities()
            : base("name=ALevelProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DicClients> DicClients { get; set; }
        public virtual DbSet<DicGoods> DicGoods { get; set; }
        public virtual DbSet<JorOrders> JorOrders { get; set; }
    }
}
